#!/usr/bin/env python3

# SPDX-License-Identifier: GPL-3.0-or-later

import os

import agent


with agent.redis_connect(privileged=True) as rdb:
    rdb.sadd(
        os.environ["AGENT_ID"] + "/roles/selfadm",
        "configure-remote-domain",
    )
