#!/usr/bin/env python3

# SPDX-License-Identifier: GPL-3.0-or-later

import json
import os
import sys

import agent
import cluster.userdomains


agent.set_weight(os.path.basename(__file__), 0)
agent.set_weight("40start_provisioning", 5)

request = json.load(sys.stdin)
realm = request["realm"].lower()

with agent.redis_connect() as rdb:
    domains = (
        cluster.userdomains.get_internal_domains(rdb)
        | cluster.userdomains.get_external_domains(rdb)
    )

if realm in domains:
    agent.set_status("validation-failed")
    json.dump(
        [
            {
                "field": "realm",
                "parameter": "realm",
                "value": realm,
                "error": "domain_already_exists",
            }
        ],
        fp=sys.stdout,
    )
    sys.exit(2)
